embedding_size: 512
feat_embed_dim: 512

epochs: 10000
n_layers: [1]
dropout: [0.3]
reg_weight: [0.01]
cl_weight: 2.0

learning_rate: 0.001
train_batch_size: 65536

use_neg_sampling: False

hyper_parameters: ["n_layers", "reg_weight", "dropout"]

