recdim: 64
layer_num: 3
reg: [0.01, 0.0001]
ssl_task: 'FAC'
learning_rate: [0.0001]
weight_decay: 1e-4
ssl_alpha: [0.01]
ssl_temp: [1.0]
dropout_rate: 0.3
mm_fusion_mode: 'concat'
temp: 0.2
init: 'xavier'
adj_type: 'pre'
hyper_parameters: ["learning_rate", "ssl_temp", "ssl_alpha", "reg"]
